version: "3.8"

services:
  app:
    container_name: connect-backend-dev
    image: connect-backend-dev
    volumes:
      - .:/app
    build:
      context: ./
      target: development
    ports:
      - 4000:4000